version: '3.8'
services:
  mkcert:
    image: mkcert
    build: ./backend/mkcert
    container_name: mkcert
    environment:
      - API_HOSTNAME=$API_HOSTNAME
      - CN=$MQTT_HOSTNAME
    volumes:
      - ./backend/mkcert/certs:/root/certs
    command: /mkcerts.sh
